In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 1. What is an autonomous machine, and what does autonomy mean?

Autonomous machines are able to accomplish their goal (in the environment) without external control. The ability of a system to operate fully under its own laws of operation, not requiring external control

# 2a. Classical AI techniques employ trees of decision constructs (if statements, etc.) to achieve some form of "intelligent"-like behavior. An example of this is the famous Eliza AI-based "psychotherapist". What do you feel are the strengths and weaknesses of such an approach? State and explain three such strengths and three weaknesses.

strengths: 1. firm decision, 2. better modelling 3. visual procedures. 

weaknesses: 1. require high level knowledge on the nature of the problem, 2. unable to fit new phenomenon, 3. complex structure

# 2b. Data Science includes signal processing, adaptive filters, supervised and unsupervised machine learning. These techniques solve the modeling problem from the perspective of the data. That is, they serve to classify signals (data), interpolate signals (data), or extract signal from noise. Comment on how these functions relate to artificial intelligence?

The artificial neural network provides the program with the ability to generalize from its experience, so that in new states it selects moves based on information saved from similar states faced in the past, as determined by the network. How well a reinforcement learning system can work in problems with such large state sets is intimately tied to how appropriately it can generalize from past experience. It is in this role that we have the greatest need for supervised learning methods within reinforcement learning. 

# 2c. Control theory concerns the development of feedback laws (i.e., control laws) that strive to push a system (the "plant") to a desired state. It does this based on observation of essential characteristics of the plant (the state, or some possibly noisy or lossy observation of the state), and construction of an appropriate feedback signal. How does this tool compare with the prior two, relating to the development of an autonomous system? Explain the similarities and differences from a structural (high level) point of view.

Control theory is based on modeling the environment and problem instead of analyzing all possible steps as done in classical digital computer algorism. Also, different from RL, control theory requires specific manually designed model for the environment and controller.

# 1. Create a python class maintains the TTT board. It should have a reset method (to clear the TTT board), methods for setting the position of the board for each player, and a method to indicate whether the game has been won (returning who has won), or whether the game is at a draw.

In [ ]:
class TTT():
  board = np.zeros((2,3,3))
  magic = np.array([[2,7,6],[9,5,1],[4,3,8]])
  def __init__(self,player):
    self.player = player
    self.moves = np.zeros((3,3))
  def move(self, state):
    self.board += state
    self.moves += state[0]
    if np.sum(self.board[0]>1) != 0:
      self.board -= state
      self.moves -= state[0]
      print("invalid move!")
      
    if np.sum(self.moves*self.magic) == 15:
      print(self.player + " won!")
      

    if np.sum(self.board[0]) == 9:
      print("draw")
      
    print(self.board)
  
  def reset(self):
    self.board *= 0
    self.moves *= 0


# 2. Test this python class, by playing a two-human game of TTT.

In [ ]:
A = TTT("player A")
B = TTT("player B")

In [ ]:
A.moves

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
A.move(np.array([[[1,0,0],[0,0,0],[0,0,0]],[[1,0,0],[0,0,0],[0,0,0]]]))

[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
B.move(np.array([[[0,0,0],[0,1,0],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.board

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
A.move(np.array([[[0,1,0],[0,0,0],[0,0,0]],[[0,1,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
B.move(np.array([[[0,0,0],[0,0,1],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 0.]
  [0. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.move(np.array([[[0,0,1],[0,0,0],[0,0,0]],[[0,0,1],[0,0,0],[0,0,0]]]))

player A won!
[[[1. 1. 1.]
  [0. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.moves

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
B.moves

array([[0., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.]])

In [ ]:
A.reset()
B.reset()

In [ ]:
B.board

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
A.move(np.array([[[1,0,0],[0,0,0],[0,0,0]],[[1,0,0],[0,0,0],[0,0,0]]]))

[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.board

array([[[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
B.board

array([[[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
B.move(np.array([[[0,0,0],[0,1,0],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.move(np.array([[[0,1,0],[0,0,0],[0,0,0]],[[0,1,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
B.move(np.array([[[0,0,1],[0,0,0],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 1.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A.move(np.array([[[0,0,0],[0,0,0],[1,0,0]],[[0,0,0],[0,0,0],[1,0,0]]]))

[[[1. 1. 1.]
  [0. 1. 0.]
  [1. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [1. 0. 0.]]]


In [ ]:
B.move(np.array([[[0,0,0],[1,0,0],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 1.]
  [1. 1. 0.]
  [1. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [1. 0. 0.]]]


In [ ]:
A.move(np.array([[[0,0,0],[0,0,1],[0,0,0]],[[0,0,0],[0,0,1],[0,0,0]]]))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 1.]
  [1. 0. 0.]]]


In [ ]:
B.move(np.array([[[0,0,0],[0,0,0],[0,0,1]],[[0,0,0],[0,0,0],[0,0,0]]]))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 0. 1.]]

 [[1. 1. 0.]
  [0. 0. 1.]
  [1. 0. 0.]]]


In [ ]:
A.move(np.array([[[0,0,0],[0,0,0],[0,1,0]],[[0,0,0],[0,0,0],[0,1,0]]]))

draw
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 0.]
  [0. 0. 1.]
  [1. 1. 0.]]]


In [ ]:
A.reset()
B.reset()

In [ ]:
B.moves

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3. Now you are to create a computer player. The goal of the computer player is to win if possible, or at worst, not lose. First think about the strategy that you need to codify, and then codify it.

In [ ]:
import time

class Game:
    def __init__(self):
        self.initialize_game()

    def initialize_game(self):
        self.current_state = [['.','.','.'],
                              ['.','.','.'],
                              ['.','.','.']]

        # Player X always plays first
        self.player_turn = 'X'

    def draw_board(self):
        for i in range(0, 3):
            for j in range(0, 3):
                print('{}|'.format(self.current_state[i][j]), end=" ")
            print()
        print()
    def is_valid(self, px, py):
      if px < 0 or px > 2 or py < 0 or py > 2:
          return False
      elif self.current_state[px][py] != '.':
          return False
      else:
          return True
    def is_end(self):
        # Vertical win
        for i in range(0, 3):
            if (self.current_state[0][i] != '.' and
                self.current_state[0][i] == self.current_state[1][i] and
                self.current_state[1][i] == self.current_state[2][i]):
                return self.current_state[0][i]

        # Horizontal win
        for i in range(0, 3):
            if (self.current_state[i] == ['X', 'X', 'X']):
                return 'X'
            elif (self.current_state[i] == ['O', 'O', 'O']):
                return 'O'

        # Main diagonal win
        if (self.current_state[0][0] != '.' and
            self.current_state[0][0] == self.current_state[1][1] and
            self.current_state[0][0] == self.current_state[2][2]):
            return self.current_state[0][0]

        # Second diagonal win
        if (self.current_state[0][2] != '.' and
            self.current_state[0][2] == self.current_state[1][1] and
            self.current_state[0][2] == self.current_state[2][0]):
            return self.current_state[0][2]

        # Is whole board full?
        for i in range(0, 3):
            for j in range(0, 3):
                # There's an empty field, we continue the game
                if (self.current_state[i][j] == '.'):
                    return None

        # It's a tie!
        return '.'
    def max(self):

        # Possible values for maxv are:
        # -1 - loss
        # 0  - a tie
        # 1  - win

        # We're initially setting it to -2 as worse than the worst case:
        maxv = -2

        px = None
        py = None

        result = self.is_end()

        # If the game came to an end, the function needs to return
        # the evaluation function of the end. That can be:
        # -1 - loss
        # 0  - a tie
        # 1  - win
        if result == 'X':
            return (-1, 0, 0)
        elif result == 'O':
            return (1, 0, 0)
        elif result == '.':
            return (0, 0, 0)

        for i in range(0, 3):
            for j in range(0, 3):
                if self.current_state[i][j] == '.':
                    # On the empty field player 'O' makes a move and calls Min
                    # That's one branch of the game tree.
                    self.current_state[i][j] = 'O'
                    (m, min_i, min_j) = self.min()
                    # Fixing the maxv value if needed
                    if m > maxv:
                        maxv = m
                        px = i
                        py = j
                    # Setting back the field to empty
                    self.current_state[i][j] = '.'
        return (maxv, px, py)
    def min(self):

        # Possible values for minv are:
        # -1 - win
        # 0  - a tie
        # 1  - loss

        # We're initially setting it to 2 as worse than the worst case:
        minv = 2

        qx = None
        qy = None

        result = self.is_end()

        if result == 'X':
            return (-1, 0, 0)
        elif result == 'O':
            return (1, 0, 0)
        elif result == '.':
            return (0, 0, 0)

        for i in range(0, 3):
            for j in range(0, 3):
                if self.current_state[i][j] == '.':
                    self.current_state[i][j] = 'X'
                    (m, max_i, max_j) = self.max()
                    if m < minv:
                        minv = m
                        qx = i
                        qy = j
                    self.current_state[i][j] = '.'

        return (minv, qx, qy)
    def play(self):
        while True:
            self.draw_board()
            self.result = self.is_end()

            # Printing the appropriate message if the game has ended
            if self.result != None:
                if self.result == 'X':
                    print('The winner is X!')
                elif self.result == 'O':
                    print('The winner is O!')
                elif self.result == '.':
                    print("It's a tie!")

                self.initialize_game()
                return

            # If it's player's turn
            if self.player_turn == 'X':

                while True:

                    start = time.time()
                    (m, qx, qy) = self.min()
                    end = time.time()
                    print('Evaluation time: {}s'.format(round(end - start, 7)))
                    print('Recommended move: X = {}, Y = {}'.format(qx, qy))

                    px = int(input('Insert the X coordinate: '))
                    py = int(input('Insert the Y coordinate: '))

                    (qx, qy) = (px, py)

                    if self.is_valid(px, py):
                        self.current_state[px][py] = 'X'
                        self.player_turn = 'O'
                        break
                    else:
                        print('The move is not valid! Try again.')

            # If it's AI's turn
            else:
                (m, px, py) = self.max()
                self.current_state[px][py] = 'O'
                self.player_turn = 'X'


In [ ]:
def main():
    g = Game()
    g.play()

if __name__ == "__main__":
    main()

.| .| .| 
.| .| .| 
.| .| .| 

Evaluation time: 3.28722s
Recommended move: X = 0, Y = 0
Insert the X coordinate: 0
Insert the Y coordinate: 0
X| .| .| 
.| .| .| 
.| .| .| 

X| .| .| 
.| O| .| 
.| .| .| 

Evaluation time: 0.0437024s
Recommended move: X = 0, Y = 1
Insert the X coordinate: 0
Insert the Y coordinate: 2
X| .| X| 
.| O| .| 
.| .| .| 

X| O| X| 
.| O| .| 
.| .| .| 

Evaluation time: 0.0015874s
Recommended move: X = 2, Y = 1
Insert the X coordinate: 2
Insert the Y coordinate: 1
X| O| X| 
.| O| .| 
.| X| .| 

X| O| X| 
O| O| .| 
.| X| .| 

Evaluation time: 9.2e-05s
Recommended move: X = 1, Y = 2
Insert the X coordinate: 1
Insert the Y coordinate: 2
X| O| X| 
O| O| X| 
.| X| .| 

X| O| X| 
O| O| X| 
.| X| O| 

Evaluation time: 2.86e-05s
Recommended move: X = 2, Y = 0
Insert the X coordinate: 2
Insert the Y coordinate: 0
X| O| X| 
O| O| X| 
X| X| O| 

It's a tie!
